import      _                                /**/ from 'lodash'
import      { CK }                                from '@freeword/meta'
import      * as FE                               from '../fastener/FastenerEnums.ts'

export const driverTargets = CK.obj({
  drives:      FE.anyFastenerSizing.optional(),
  drives_alt:  FE.anyFastenerSizing.optional(),
  exthex_sz:   FE.anyFastenerSizing.optional(),
  hhcs_sz:     FE.anyFastenerSizing.optional(),
  hn_sz:       FE.anyFastenerSizing.optional(),
  hhn_sz:      FE.anyFastenerSizing.optional(),
  shcs_sz:     FE.fastenerSizing.optional(),
  fhcs_sz:     FE.fastenerSizing.optional(),
  bhcs_sz:     FE.fastenerSizing.optional(),
  sss_sz:      FE.fastenerSizing.optional(),
  losock_sz:   FE.fastenerSizing.optional(),
})
export const driveToDriven = CK.obj({
  unit_system: CK.oneof(['in', 'mm']),
  driver_sz: FE.driver_sz,
  ...driverTargets.shape,
}).strict()
export interface DriverTargetsT extends CK.Zcasted<typeof driverTargets> {}
export interface DriveToDrivenT extends CK.Zcasted<typeof driveToDriven> {}

export const DriveToDriven = {
  "Wr3/16in":     { driver_sz: "Wr3/16in",     unit_system: "in", drives: "#2",        exthex_sz: "#2",        hhcs_sz: "#2",      hn_sz: "N#2",                                           },
  "Wr7/32in":     { driver_sz: "Wr7/32in",     unit_system: "in" },
  "Wr1/4in":      { driver_sz: "Wr1/4in",      unit_system: "in", drives: "#4",        exthex_sz: "#4",        hhcs_sz: "#4",      hn_sz: "N#4",                                           },
  "Wr9/32in":     { driver_sz: "Wr9/32in",     unit_system: "in" },
  "Wr5/16in":     { driver_sz: "Wr5/16in",     unit_system: "in", drives: "#6",        exthex_sz: "#6",        hhcs_sz: "#6",      hn_sz: "N#6",                                           },
  "Wr11/32in":    { driver_sz: "Wr11/32in",    unit_system: "in", drives: "#8",        exthex_sz: "#8",        hhcs_sz: "#8",      hn_sz: "N#8",                                           },
  "Wr3/8in":      { driver_sz: "Wr3/8in",      unit_system: "in", drives: "#10",       exthex_sz: "#10",       hhcs_sz: "#10",     hn_sz: "N#10",                                          },
  "Wr7/16in":     { driver_sz: "Wr7/16in",     unit_system: "in", drives: "1/4in",     exthex_sz: "1/4in",     hhcs_sz: "1/4in",   hn_sz: "N1/4in",                                        },
  "Wr1/2in":      { driver_sz: "Wr1/2in",      unit_system: "in", drives: "5/16in",    exthex_sz: "5/16in",    hhcs_sz: "5/16in",  hn_sz: "N5/16in",  hhn_sz: "HN1/4in"                    },
  "Wr9/16in":     { driver_sz: "Wr9/16in",     unit_system: "in", drives: "3/8in",     exthex_sz: "3/8in",     hhcs_sz: "3/8in",   hn_sz: "N3/8in",   hhn_sz: "HN5/16in"                   },
  "Wr5/8in":      { driver_sz: "Wr5/8in",      unit_system: "in", drives: "7/16in",    exthex_sz: "7/16in",    hhcs_sz: "7/16in",  hn_sz: "N7/16in",                                       },
  "Wr11/16in":    { driver_sz: "Wr11/16in",    unit_system: "in", drives: "HN3/8in",   exthex_sz: "HN3/8in",                                          hhn_sz: "HN3/8in"                    },
  "Wr3/4in":      { driver_sz: "Wr3/4in",      unit_system: "in", drives: "1/2in",     exthex_sz: "1/2in",     hhcs_sz: "1/2in",   hn_sz: "N1/2in",   hhn_sz: "HN7/16in"                   },
  "Wr13/16in":    { driver_sz: "Wr13/16in",    unit_system: "in", drives: "HN1/2in",   exthex_sz: "HN1/2in",                                          hhn_sz: "HN1/2in"                    },
  "Wr7/8in":      { driver_sz: "Wr7/8in",      unit_system: "in", drives: "9/16in",    exthex_sz: "9/16in",    hhcs_sz: "9/16in",  hn_sz: "N9/16in",                                       },
  "Wr15/16in":    { driver_sz: "Wr15/16in",    unit_system: "in", drives: "5/8in",     exthex_sz: "5/8in",     hhcs_sz: "5/8in",   hn_sz: "N5/8in",                                        },
  "Wr1in":        { driver_sz: "Wr1in",        unit_system: "in" },
  "Wr1+1/16in":   { driver_sz: "Wr1+1/16in",   unit_system: "in", drives: "3/4in",     exthex_sz: "3/4in",     hhcs_sz: "3/4in",   hn_sz: "N3/4in",   hhn_sz: "HN5/8in"                    },
  "Wr1+1/8in":    { driver_sz: "Wr1+1/8in",    unit_system: "in", drives: "3/4in"                                                                                                         },
  "Wr1+1/4in":    { driver_sz: "Wr1+1/4in",    unit_system: "in", drives: "HN3/4in",   exthex_sz: "HN3/4in",                                          hhn_sz: "HN3/4in"                    },
  "Wr1+5/16in":   { driver_sz: "Wr1+5/16in",   unit_system: "in", drives: "7/8in",     exthex_sz: "7/8in",     hhcs_sz: "7/8in",   hn_sz: "N7/8in",                                        },
  "Wr1+7/16in":   { driver_sz: "Wr1+7/16in",   unit_system: "in", drives: "HN7/8in",   exthex_sz: "HN7/8in",                                          hhn_sz: "HN7/8in"                    },
  "Wr1+1/2in":    { driver_sz: "Wr1+1/2in",    unit_system: "in", drives: "1in",       exthex_sz: "1in",       hhcs_sz: "1in",     hn_sz: "N1in",                                          },
  "Wr1+5/8in":    { driver_sz: "Wr1+5/8in",    unit_system: "in", drives: "HN1in",     exthex_sz: "HN1in",                                            hhn_sz: "HN1in"                      },
  "Wr1+11/16in":  { driver_sz: "Wr1+11/16in",  unit_system: "in", drives: "1+1/8in",   exthex_sz: "1+1/8in",   hhcs_sz: "1+1/8in", hn_sz: "N1+1/8in",                                      },
  "Wr1+13/16in":  { driver_sz: "Wr1+13/16in",  unit_system: "in", drives: "HN1+1/8in", exthex_sz: "HN1+1/8in",                                        hhn_sz: "HN1+1/8in"                  },
  "Wr1+7/8in":    { driver_sz: "Wr1+7/8in",    unit_system: "in", drives: "1+1/4in",   exthex_sz: "1+1/4in",   hhcs_sz: "1+1/4in", hn_sz: "N1+1/4in",                                      },
  "Wr2in":        { driver_sz: "Wr2in",        unit_system: "in", drives: "HN1+1/4in", exthex_sz: "HN1+1/4in",                                        hhn_sz: "HN1+1/4in"                  },
  "Wr2+1/16in":   { driver_sz: "Wr2+1/16in",   unit_system: "in", drives: "1+3/8in",   exthex_sz: "1+3/8in",   hhcs_sz: "1+3/8in", hn_sz: "N1+3/8in",                                      },
  "Wr2+3/16in":   { driver_sz: "Wr2+3/16in",   unit_system: "in", drives: "HN1+3/8in", exthex_sz: "HN1+3/8in",                                        hhn_sz: "HN1+3/8in"                  },
  "Wr2+1/4in":    { driver_sz: "Wr2+1/4in",    unit_system: "in", drives: "1+1/2in",   exthex_sz: "1+1/2in",   hhcs_sz: "1+1/2in", hn_sz: "N1+1/2in",                                      },
  "Wr2+3/8in":    { driver_sz: "Wr2+3/8in",    unit_system: "in", drives: "HN1+1/2in", exthex_sz: "HN1+1/2in",                                        hhn_sz: "HN1+1/2in"                  },
  "Wr2+5/8in":    { driver_sz: "Wr2+5/8in",    unit_system: "in", drives: "1+3/4in",   exthex_sz: "1+3/4in",   hhcs_sz: "1+3/4in", hn_sz: "N1+3/4in",                                      },
  "Wr2+3/4in":    { driver_sz: "Wr2+3/4in",    unit_system: "in", drives: "HN1+3/4in", exthex_sz: "HN1+3/4in",                                        hhn_sz: "HN1+3/4in"                  },
  "Wr3in":        { driver_sz: "Wr3in",        unit_system: "in", drives: "2in",       exthex_sz: "2in",       hhcs_sz: "2in",     hn_sz: "N2in",                                          },
  "Wr3+1/8in":    { driver_sz: "Wr3+1/8in",    unit_system: "in", drives: "HN2in",     exthex_sz: "HN2in",                                            hhn_sz: "HN2in"                      },
  "Wr3+3/8in":    { driver_sz: "Wr3+3/8in",    unit_system: "in", drives: "2+1/4in",   exthex_sz: "2+1/4in",   hhcs_sz: "2+1/4in", hn_sz: "N2+1/4in",                                      },
  "Wr3+1/2in":    { driver_sz: "Wr3+1/2in",    unit_system: "in", drives: "HN2+1/4in", exthex_sz: "HN2+1/4in",                                        hhn_sz: "HN2+1/4in"                  },
  "Wr3+3/4in":    { driver_sz: "Wr3+3/4in",    unit_system: "in", drives: "2+1/2in",   exthex_sz: "2+1/2in",   hhcs_sz: "2+1/2in", hn_sz: "N2+1/2in",                                      },
  "Wr3+7/8in":    { driver_sz: "Wr3+7/8in",    unit_system: "in", drives: "HN2+1/2in", exthex_sz: "HN2+1/2in",                                        hhn_sz: "HN2+1/2in"                  },
  "Wr4+1/8in":    { driver_sz: "Wr4+1/8in",    unit_system: "in", drives: "2+3/4in",   exthex_sz: "2+3/4in",   hhcs_sz: "2+3/4in", hn_sz: "N2+3/4in",                                      },
  "Wr4+1/4in":    { driver_sz: "Wr4+1/4in",    unit_system: "in", drives: "HN2+3/4in", exthex_sz: "HN2+3/4in",                                        hhn_sz: "HN2+3/4in"                  },
  "Wr4+1/2in":    { driver_sz: "Wr4+1/2in",    unit_system: "in", drives: "3in",       exthex_sz: "3in",       hhcs_sz: "3in",     hn_sz: "N3in",                                          },
  "Wr4mm":        { driver_sz: "Wr4mm",        unit_system: "mm", drives: "M2",        exthex_sz: "M2",        hhcs_sz: "M2",      hn_sz: "NM2",      hhn_sz: "HNM2"                       },
  "Wr5mm":        { driver_sz: "Wr5mm",        unit_system: "mm", drives: "M2.5",      exthex_sz: "M2.5",      hhcs_sz: "M2.5",    hn_sz: "NM2.5",    hhn_sz: "HNM2.5"                     },
  "Wr5.5mm":      { driver_sz: "Wr5.5mm",      unit_system: "mm", drives: "M3",        exthex_sz: "M3",        hhcs_sz: "M3",      hn_sz: "NM3",      hhn_sz: "HNM3"                       },
  "Wr6mm":        { driver_sz: "Wr6mm",        unit_system: "mm" },
  "Wr7mm":        { driver_sz: "Wr7mm",        unit_system: "mm", drives: "M4",        exthex_sz: "M4",        hhcs_sz: "M4",      hn_sz: "NM4",      hhn_sz: "HNM4"                       },
  "Wr8mm":        { driver_sz: "Wr8mm",        unit_system: "mm", drives: "M5",        exthex_sz: "M5",        hhcs_sz: "M5",      hn_sz: "NM5",      hhn_sz: "HNM5"                       },
  "Wr9mm":        { driver_sz: "Wr9mm",        unit_system: "mm" },
  "Wr10mm":       { driver_sz: "Wr10mm",       unit_system: "mm", drives: "M6",        exthex_sz: "M6",        hhcs_sz: "M6",      hn_sz: "NM6",      hhn_sz: "HNM6"                       },
  "Wr11mm":       { driver_sz: "Wr11mm",       unit_system: "mm" },
  "Wr12mm":       { driver_sz: "Wr12mm",       unit_system: "mm", drives: "D8",        exthex_sz: "D8",        hhcs_sz: "D8",      hn_sz: "ND8",      hhn_sz: "HND8"                       },
  "Wr13mm":       { driver_sz: "Wr13mm",       unit_system: "mm", drives: "M8",        exthex_sz: "M8",        hhcs_sz: "M8",      hn_sz: "NM8",      hhn_sz: "HNM8"                       },
  "Wr14mm":       { driver_sz: "Wr14mm",       unit_system: "mm" },
  "Wr15mm":       { driver_sz: "Wr15mm",       unit_system: "mm" },
  "Wr16mm":       { driver_sz: "Wr16mm",       unit_system: "mm", drives: "D10",       exthex_sz: "D10",       hhcs_sz: "D10",     hn_sz: "ND10",     hhn_sz: "HND10"                      },
  "Wr17mm":       { driver_sz: "Wr17mm",       unit_system: "mm", drives: "M10",       exthex_sz: "M10",       hhcs_sz: "M10",     hn_sz: "NM10",     hhn_sz: "HNM10"                      },
  "Wr18mm":       { driver_sz: "Wr18mm",       unit_system: "mm", drives: "D12",       exthex_sz: "D12",       hhcs_sz: "D12",     hn_sz: "ND12",     hhn_sz: "HND12"                      },
  "Wr19mm":       { driver_sz: "Wr19mm",       unit_system: "mm", drives: "M12",       exthex_sz: "M12",       hhcs_sz: "M12",     hn_sz: "NM12",     hhn_sz: "HNM12"                      },
  "Wr21mm":       { driver_sz: "Wr21mm",       unit_system: "mm", drives: "D14",       exthex_sz: "D14",       hhcs_sz: "D14",     hn_sz: "ND14",     hhn_sz: "HND14"                      },
  "Wr22mm":       { driver_sz: "Wr22mm",       unit_system: "mm", drives: "M14",       exthex_sz: "M14",       hhcs_sz: "M14",     hn_sz: "NM14",     hhn_sz: "HNM14"                      },
  "Wr24mm":       { driver_sz: "Wr24mm",       unit_system: "mm", drives: "M16",       exthex_sz: "M16",       hhcs_sz: "M16",     hn_sz: "NM16",     hhn_sz: "HNM16"                      },
  "Wr27mm":       { driver_sz: "Wr27mm",       unit_system: "mm", drives: "M18",       exthex_sz: "M18",       hhcs_sz: "M18",     hn_sz: "NM18",     hhn_sz: "HNM18"                      },
  "Wr30mm":       { driver_sz: "Wr30mm",       unit_system: "mm", drives: "M20",       exthex_sz: "M20",       hhcs_sz: "M20",     hn_sz: "NM20",     hhn_sz: "HNM20"                      },
  "Wr34mm":       { driver_sz: "Wr34mm",       unit_system: "mm", drives: "M22",       exthex_sz: "M22",       hhcs_sz: "M22",     hn_sz: "NM22",     hhn_sz: "HNM22"                      },
  "Wr36mm":       { driver_sz: "Wr36mm",       unit_system: "mm", drives: "M24",       exthex_sz: "M24",       hhcs_sz: "M24",     hn_sz: "NM24",     hhn_sz: "HNM24"                      },
  "Wr41mm":       { driver_sz: "Wr41mm",       unit_system: "mm", drives: "M27",       exthex_sz: "M27",       hhcs_sz: "M27",     hn_sz: "NM27",     hhn_sz: "HNM27"                      },
  "Wr46mm":       { driver_sz: "Wr46mm",       unit_system: "mm", drives: "M30",       exthex_sz: "M30",       hhcs_sz: "M30",     hn_sz: "NM30",     hhn_sz: "HNM30"                      },
  "Wr50mm":       { driver_sz: "Wr50mm",       unit_system: "mm", drives: "M33",       exthex_sz: "M33",       hhcs_sz: "M33",     hn_sz: "NM33",     hhn_sz: "HNM33"                      },
  "Wr55mm":       { driver_sz: "Wr55mm",       unit_system: "mm", drives: "M36",       exthex_sz: "M36",       hhcs_sz: "M36",     hn_sz: "NM36",     hhn_sz: "HNM36"                      },
  "Wr60mm":       { driver_sz: "Wr60mm",       unit_system: "mm", drives: "M39",       exthex_sz: "M39",       hhcs_sz: "M39",     hn_sz: "NM39",     hhn_sz: "HNM39"                      },
  "Wr65mm":       { driver_sz: "Wr65mm",       unit_system: "mm", drives: "M42",       exthex_sz: "M42",       hhcs_sz: "M42",     hn_sz: "NM42",     hhn_sz: "HNM42"                      },
  "H0.028in":     { driver_sz: "H0.028in",     unit_system: "in",                                                                                     sss_sz: "#0",                       },
  "H0.035in":     { driver_sz: "H0.035in",     unit_system: "in",                                              drives_alt: "#0",    fhcs_sz: "#0",      bhcs_sz: "#0",     sss_sz: "#2",                       },
  "H0.050in":     { driver_sz: "H0.050in",     unit_system: "in", drives: "#0",        shcs_sz: "#0",          drives_alt: "#2",    fhcs_sz: "#2",      bhcs_sz: "#2",     sss_sz: "#4",                       },
  "H1/16in":      { driver_sz: "H1/16in",      unit_system: "in", drives: "#1",        shcs_sz: "#1",          drives_alt: "#4",    fhcs_sz: "#4",      bhcs_sz: "#4",     sss_sz: "#6",                       },
  "H5/64in":      { driver_sz: "H5/64in",      unit_system: "in", drives: "#2",        shcs_sz: "#2",          drives_alt: "#6",    fhcs_sz: "#6",      bhcs_sz: "#6",     sss_sz: "#8",                       },
  "H3/32in":      { driver_sz: "H3/32in",      unit_system: "in", drives: "#4",        shcs_sz: "#4",          drives_alt: "#8",    fhcs_sz: "#8",      bhcs_sz: "#8",     sss_sz: "#10",                      },
  "H7/64in":      { driver_sz: "H7/64in",      unit_system: "in", drives: "#6",        shcs_sz: "#6",                                                                                  },
  "H1/8in":       { driver_sz: "H1/8in",       unit_system: "in",                                              drives_alt: "#10",   fhcs_sz: "#10",     bhcs_sz: "#10",    sss_sz: "1/4in",                    },
  "H9/64in":      { driver_sz: "H9/64in",      unit_system: "in", drives: "#8",        shcs_sz: "#8",        },
  "H5/32in":      { driver_sz: "H5/32in",      unit_system: "in", drives: "#10",       shcs_sz: "#10",         drives_alt: "1/4in", fhcs_sz: "1/4in",   bhcs_sz: "1/4in",  sss_sz: "5/16in",                   },
  "H3/16in":      { driver_sz: "H3/16in",      unit_system: "in", drives: "1/4in",     shcs_sz: "1/4in",       drives_alt: "5/16in",fhcs_sz: "5/16in",  bhcs_sz: "5/16in", sss_sz: "3/8in",                    },
  "H7/32in":      { driver_sz: "H7/32in",      unit_system: "in",                                              drives_alt: "3/8in", fhcs_sz: "3/8in",   bhcs_sz: "3/8in",  sss_sz: "7/16in",                   },
  "H1/4in":       { driver_sz: "H1/4in",       unit_system: "in", drives: "5/16in",    shcs_sz: "5/16in",      drives_alt: "7/16in",fhcs_sz: "7/16in",  bhcs_sz: "7/16in", sss_sz: "1/2in",                    },
  "H5/16in":      { driver_sz: "H5/16in",      unit_system: "in", drives: "3/8in",     shcs_sz: "3/8in",       drives_alt: "1/2in", fhcs_sz: "1/2in",   bhcs_sz: "1/2in",  sss_sz: "5/8in",                    },
  "H3/8in":       { driver_sz: "H3/8in",       unit_system: "in", drives: "1/2in",     shcs_sz: "1/2in",       drives_alt: "5/8in", fhcs_sz: "5/8in",   bhcs_sz: "5/8in",  sss_sz: "3/4in",                    },
  "H7/16in":      { driver_sz: "H7/16in",      unit_system: "in", drives: "9/16in",    shcs_sz: "9/16in"     },
  "H1/2in":       { driver_sz: "H1/2in",       unit_system: "in", drives: "5/8in",     shcs_sz: "5/8in",       drives_alt: "3/4in", fhcs_sz: "3/4in",   bhcs_sz: "3/4in",  sss_sz: "7/8in",                    },
  "H9/16in":      { driver_sz: "H9/16in",      unit_system: "in",                                              drives_alt: "7/8in", fhcs_sz: "7/8in",   bhcs_sz: "7/8in",  sss_sz: "1in",                      },
  "H5/8in":       { driver_sz: "H5/8in",       unit_system: "in", drives: "3/4in",     shcs_sz: "3/4in",       drives_alt: "1in",   fhcs_sz: "1in",     bhcs_sz: "1in",                                        },
  "H3/4in":       { driver_sz: "H3/4in",       unit_system: "in", drives: "7/8in",     shcs_sz: "7/8in" },
  "H11/16in":     { driver_sz: "H11/16in",     unit_system: "in" },
  "H7/8in":       { driver_sz: "H7/8in",       unit_system: "in", drives: "1+1/4in",   shcs_sz: "1+1/4in",                                                                                                },
  "H1in":         { driver_sz: "H1in",         unit_system: "in", drives: "1+1/2in",   shcs_sz: "1+1/2in",                                                                                                },
  "H0.7mm":       { driver_sz: "H0.7mm",       unit_system: "mm",                                                                                                     sss_sz: "M1.6",                     },
  "H0.9mm":       { driver_sz: "H0.9mm",       unit_system: "mm",                                              drives_alt: "M1.6",  fhcs_sz: "M1.6",   bhcs_sz: "M1.6",   sss_sz: "M2",                       },
  "H1.3mm":       { driver_sz: "H1.3mm",       unit_system: "mm", drives: "M1.4",      shcs_sz: "M1.4",        drives_alt: "M2",    fhcs_sz: "M2",     bhcs_sz: "M2",     sss_sz: "M2.5",   losock_sz: "M2"   },
  "H1.5mm":       { driver_sz: "H1.5mm",       unit_system: "mm", drives: "M2",        shcs_sz: "M2",          drives_alt: "M2.5",  fhcs_sz: "M2.5",   bhcs_sz: "M2.5",   sss_sz: "M3",     losock_sz: "M2.5" },
  "H2mm":         { driver_sz: "H2mm",         unit_system: "mm", drives: "M2.5",      shcs_sz: "M2.5",        drives_alt: "M3",    fhcs_sz: "M3",     bhcs_sz: "M3",     sss_sz: "M4",     losock_sz: "M3"   },
  "H2.5mm":       { driver_sz: "H2.5mm",       unit_system: "mm", drives: "M3",        shcs_sz: "M3",          drives_alt: "M4",    fhcs_sz: "M4",     bhcs_sz: "M4",     sss_sz: "M5",     losock_sz: "M4"   },
  "H3mm":         { driver_sz: "H3mm",         unit_system: "mm", drives: "M4",        shcs_sz: "M4",          drives_alt: "M5",    fhcs_sz: "M5",     bhcs_sz: "M5",     sss_sz: "M6",     losock_sz: "M5"   },
  "H4mm":         { driver_sz: "H4mm",         unit_system: "mm", drives: "M5",        shcs_sz: "M5",          drives_alt: "M6",    fhcs_sz: "M6",     bhcs_sz: "M6",     sss_sz: "M8",     losock_sz: "M6"   },
  "H5mm":         { driver_sz: "H5mm",         unit_system: "mm", drives: "M6",        shcs_sz: "M6",          drives_alt: "M8",    fhcs_sz: "M8",     bhcs_sz: "M8",     sss_sz: "M10",    losock_sz: "M8"   },
  "H6mm":         { driver_sz: "H6mm",         unit_system: "mm", drives: "M8",        shcs_sz: "M8",          drives_alt: "M10",   fhcs_sz: "M10",    bhcs_sz: "M10",    sss_sz: "M12",    losock_sz: "M10"  },
  "H7mm":         { driver_sz: "H7mm",         unit_system: "mm" },
  "H8mm":         { driver_sz: "H8mm",         unit_system: "mm", drives: "M10",       shcs_sz: "M10",         drives_alt: "M12",   fhcs_sz: "M12",    bhcs_sz: "M12",                      losock_sz: "M12"  },
  "H9mm":         { driver_sz: "H9mm",         unit_system: "mm",                                              drives_alt: "M16" },
  "H10mm":        { driver_sz: "H10mm",        unit_system: "mm", drives: "M12",       shcs_sz: "M12",         drives_alt: "M16",   fhcs_sz: "M16",    bhcs_sz: "M16",    sss_sz: "M20"                       },
  "H11mm":        { driver_sz: "H11mm",        unit_system: "mm" },
  "H12mm":        { driver_sz: "H12mm",        unit_system: "mm", drives: "M14",       shcs_sz: "M14",         drives_alt: "M20",   fhcs_sz: "M20",    bhcs_sz: "M20",    sss_sz: "M24"                       },
  "H13mm":        { driver_sz: "H13mm",        unit_system: "mm" },
  "H14mm":        { driver_sz: "H14mm",        unit_system: "mm", drives: "M16",       shcs_sz: "M16",         drives_alt: "M24",   fhcs_sz: "M24",    bhcs_sz: "M24",                      losock_sz: "M16"  },
  "H15mm":        { driver_sz: "H15mm",        unit_system: "mm" },
  "H17mm":        { driver_sz: "H17mm",        unit_system: "mm", drives: "M20",       shcs_sz: "M20",                                                                losock_sz: "M20"  },
  "H19mm":        { driver_sz: "H19mm",        unit_system: "mm", drives: "M24",       shcs_sz: "M24"                                                                                   },
  "H22mm":        { driver_sz: "H22mm",        unit_system: "mm", drives: "M30",       shcs_sz: "M30"                                                                                   },
  "H27mm":        { driver_sz: "H27mm",        unit_system: "mm", drives: "M36",       shcs_sz: "M36"                                                                                   },
  "H32mm":        { driver_sz: "H32mm",        unit_system: "mm", drives: "M42",       shcs_sz: "M42"                                                                                   },

  "T1":    { unit_system: "mm", driver_sz: "T1" },
  "T2":    { unit_system: "mm", driver_sz: "T2" },
  "T3":    { unit_system: "mm", driver_sz: "T3" },
  "T4":    { unit_system: "mm", driver_sz: "T4", drives_alt: "#0" },
  "T5":    { unit_system: "mm", driver_sz: "T5", drives_alt: "#1" },
  "T6":    { unit_system: "mm", driver_sz: "T6", drives: "M2", drives_alt: "#2" },
  "T7":    { unit_system: "mm", driver_sz: "T7", drives: "M2.5", drives_alt: "#3" },
  "T8":    { unit_system: "mm", driver_sz: "T8", drives: "M2.5", drives_alt: "#4" },
  "T9":    { unit_system: "mm", driver_sz: "T9", drives: "M3", drives_alt: "#5" },
  "T10":   { unit_system: "mm", driver_sz: "T10", drives: "M3", drives_alt: "#6" },
  "T15":   { unit_system: "mm", driver_sz: "T15", drives: "M3.5", drives_alt: "#6" },
  "T20":   { unit_system: "mm", driver_sz: "T20", drives: "M4", drives_alt: "#8" },
  "T25":   { unit_system: "mm", driver_sz: "T25", drives: "M4.5", drives_alt: "#10" },
  "T27":   { unit_system: "mm", driver_sz: "T27", drives: "M5", drives_alt: "#12" },
  "T30":   { unit_system: "mm", driver_sz: "T30", drives: "M6", drives_alt: "1/4in" },
  "T35":   { unit_system: "mm", driver_sz: "T35" },
  "T40":   { unit_system: "mm", driver_sz: "T40", drives: "M8", drives_alt: "5/16in" },
  "T45":   { unit_system: "mm", driver_sz: "T45", drives: "M8", drives_alt: "3/8in" },
  "T47":   { unit_system: "mm", driver_sz: "T47" },
  "T50":   { unit_system: "mm", driver_sz: "T50", drives: "M10", drives_alt: "7/16in" },
  "T55":   { unit_system: "mm", driver_sz: "T55", drives: "M12", drives_alt: "1/2in" },
  "T60":   { unit_system: "mm", driver_sz: "T60", drives: "M14", drives_alt: "9/16in" },
  "T70":   { unit_system: "mm", driver_sz: "T70", drives: "M16", drives_alt: "5/8in" },
  "T80":   { unit_system: "mm", driver_sz: "T80", drives: "M18", drives_alt: "3/4in" },
  "T90":   { unit_system: "mm", driver_sz: "T90", drives: "M20", drives_alt: "7/8in" },
  "T100":  { unit_system: "mm", driver_sz: "T100", drives: "M24", drives_alt: "1in" },

} satisfies { [key in typeof FE.MetricWrenchSizingValsA[number] | typeof FE.USWrenchSizingValsA[number] | FE.HexkeySizing | FE.TorxkeySizing]: DriveToDrivenT & { driver_sz: key } }
